platform :ios, “10.0”
use_frameworks!

pod ‘Firebase/Storage’
pod ‘Firebase/Auth’
pod ‘Firebase/Database’
pod ‘JSQMessagesViewController’

target '심부름 목록_Sample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 심부름 목록_Sample

end
